### ISSUE TITLE
launchMenu.ahk - documentation missing / error in TreeMenuUtils.ahk

### ISSUE THREAD

**Issue by emp-00** [gedoor/ahkLauncher#1]
Could you please add some documentation how to use ahkLauncher.ahk? The screenshots on the README page are only an illustration - some introduction and explanation, if posssible in English, would be great.

I would like to use your script but when running "AhkLauncher.ahk" I always get below error. Please help! Thanks you very much.

launchMenu.ahk
Error: The requested key, section or file was not found.
	---- C:\Users\XXXXDownloads\ahkLaucher\lib\TreeMenuUtils.ahk
	084: If fExt = "url"
	085: {
▶	086: OutIcon := IniRead(fPath, "InternetShortcut", "IconFile")
	087: OutIconNum := IniRead(fPath, "InternetShortcut", "IconIndex", 0)
	088: If FileExist(OutIcon)
The current thread will exit.

**Comment by Sopwith** [comment]
I am also interested in any AHK working code that can get an application jumplist, so I would like to echo the desire to see some documentation, or have an example for how to use it, if it is working. Thanks!

**Comment by gedoor** [comment]
> Could you please add some documentation how to use ahkLauncher.ahk? The screenshots on the README page are only an illustration - some introduction and explanation, if posssible in English, would be great.
> 
> I would like to use your script but when running "AhkLauncher.ahk" I always get below error. Please help! Thanks you very much.
> 
> launchMenu.ahk Error: The requested key, section or file was not found. ---- C:\Users\XXXXDownloads\ahkLaucher\lib\TreeMenuUtils.ahk 084: If fExt = "url" 085: { ▶ 086: OutIcon := IniRead(fPath, "InternetShortcut", "IconFile") 087: OutIconNum := IniRead(fPath, "InternetShortcut", "IconIndex", 0) 088: If FileExist(OutIcon) The current thread will exit.

Fixed it
